language: python
python:
  - "3.6"
  - "3.7"

branches:
  only:
    - master

install:
  - pip install .[tfa,tune,envs]
  - pip install pygame git+https://github.com/ntasfi/PyGame-Learning-Environment.git

script:
  - pytest

notifications:
  email:
    recipients:
      - tensorforce.team@gmail.com
    on_success: never
    on_failure: always
